const vendors=[
{id:'brown',name:'Brown Crust Bakery',category:'Bakery',area:'Navrangpura',distance:1.2,veg:true,portion:'2–3 savoury bakery items · light meal for one',diet:'Vegetarian · egg-free recipe; shared kitchen',allergens:'Contains wheat and milk. May contain nuts, soy and traces of egg. Not vegan.',image:'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=85'},
{id:'green',name:'The Green Cup',category:'Café',area:'University Road',distance:1.8,veg:true,portion:'1 sandwich + 1 baked treat · light meal for one',diet:'Vegetarian · egg-free recipe; shared kitchen',allergens:'Contains wheat and milk. May contain soy, nuts and traces of egg. Not vegan.',image:'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=85'},
{id:'crumb',name:'Crumb & Co.',category:'Bakery',area:'Vastrapur',distance:2.4,veg:false,portion:'2–3 sweet pastries · snack for one or two',diet:'Contains egg · not suitable for strict vegetarians',allergens:'Contains wheat, milk and egg. May contain nuts and soy. Not vegan.',image:'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=900&q=85'}];
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nextDay=()=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(p=>[p.type,p.value]));return new Date(Date.UTC(+p.year,+p.month-1,+p.day+(+p.hour>=18?1:0))).toISOString().slice(0,10)};
let customer;try{customer=localStorage.getItem('lastbite-customer')}catch{}if(!/^[a-f0-9]{64}$/.test(customer||'')){customer=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');try{localStorage.setItem('lastbite-customer',customer)}catch{}}
let slots=[],orders=[],feedback=[],filter='All',selected=null,vendorKey='',stockLoaded=false,refreshVersion=0;
const dialog=$('#reserve-dialog'),dateControl=$('#collection-date');dateControl.min=nextDay();dateControl.max=new Date(Date.parse(nextDay()+'T00:00:00Z')+13*86400000).toISOString().slice(0,10);dateControl.value=nextDay();
async function api(path,{method='GET',body,operator=false}={}){const headers={'X-Customer-Token':customer};if(operator)headers['X-Vendor-Key']=vendorKey;if(body)headers['Content-Type']='application/json';const response=await fetch(path,{method,headers,body:body?JSON.stringify(body):undefined});let data;try{data=await response.json()}catch{throw Error('The service is unavailable. Please try again.')}if(!response.ok)throw Error(data.error||'Unable to complete this request.');return data}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',5000)}
function slot(v){return slots.find(s=>s.vendor===v.id)}
function maps(v,address){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(address||`${v.area}, Ahmedabad, India`)}
function render(){const q=$('#search').value.toLowerCase();const list=vendors.filter(v=>(filter==='All'||v.category===filter||(filter==='Vegetarian'&&v.veg))&&`${v.name} ${v.area} ${v.category}`.toLowerCase().includes(q)).sort((a,b)=>$('#sort').value==='stock'?(slot(b)?.remaining||0)-(slot(a)?.remaining||0):a.distance-b.distance);$('#cards').innerHTML=list.map(v=>{const s=slot(v),available=stockLoaded&&s?.confirmed&&s.remaining>0;return `<article class="card"><div class="card-image"><img src="${v.image}" alt="Illustrative bakery food" loading="lazy"><span class="stock">${!stockLoaded?'Checking stock':s?.confirmed?s.remaining+' bags left':'Awaiting confirmation'}</span><span class="partner">ZERO-WASTE PARTNER · SAMPLE</span></div><div class="card-body"><div class="card-meta"><span>${v.category} · ${v.veg?'Vegetarian':'Contains egg'}</span><span>↗ ${v.distance} km</span></div><h3>${v.name}</h3><p>${v.area} · Sample partner</p><div class="bag-clues"><b>${v.portion}</b><span>${v.diet}</span><span>${v.allergens}</span><small>Example bag promise; exact items vary. Photos are illustrative.</small></div><div class="pickup">◷ ${esc(dateControl.value)} · 8:30–10:00 pm IST<br>Reserve by 6 pm IST · ${s?.confirmed?'Quota confirmed':'Quota not yet confirmed'}<br>${esc(s?.address||'Exact pickup address not verified')}<br><a target="_blank" rel="noopener" href="${maps(v,s?.address)}">${s?.address?'Open pickup directions ↗':'Explore sample neighbourhood ↗'}</a></div><div class="card-bottom"><span class="price">₹99 <s>₹250+</s></span><button class="primary" data-reserve="${v.id}" ${available?'':'disabled'}>${available?'Reserve a bag':s?.confirmed?'Sold out':'Not open yet'}</button></div></div></article>`}).join('')||'<div class="no-results">No bags match. Try another neighbourhood or category.</div>';$('#count').textContent=orders.filter(o=>o.status==='reserved').length;renderOrders()}
async function refresh(){const version=++refreshVersion;stockLoaded=false;$('#availability-status').textContent='Checking confirmed stock…';render();try{const data=await api('/api/slots?date='+dateControl.value);if(version!==refreshVersion)return;slots=data.slots;stockLoaded=true;dateControl.min=data.minDate;dateControl.max=data.maxDate;$('#availability-status').textContent='Only confirmed daily quotas are reservable.';render()}catch(e){if(version!==refreshVersion)return;slots=[];stockLoaded=false;$('#availability-status').textContent=e.message;render()}}
async function loadOrders(){try{orders=(await api('/api/orders')).orders;render()}catch(e){toast(e.message)}}
function view(id){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==id);document.querySelectorAll('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===id));window.scrollTo(0,0);if(id==='bags')loadOrders()}
function startReservation(id){selected=vendors.find(v=>v.id===id);if(!selected)throw Error('Unknown bag');const s=slot(selected);if(!stockLoaded||!s?.confirmed||s.remaining<1)throw Error('This daily quota is not available. Refresh stock.');$('#reserve-form').reset();$('#dialog-title').textContent=selected.name;$('#dialog-desc').textContent='A surprise within these bag clues. Exact items depend on surplus.';$('#allergens').textContent=selected.allergens;$('#bag-clues').textContent=selected.portion+' · '+selected.diet;$('#pickup-address').textContent=s.address||'Sample partner: exact pickup address not verified.';const date=$('#reserve-form input[name=date]');date.value=dateControl.value;date.readOnly=true;date.min=dateControl.min;date.max=dateControl.max;$('#reserve-error').textContent='';dialog.showModal();return {vendor:selected.name,date:dateControl.value,demo:true}}
function renderOrders(){$('#orders').innerHTML=orders.length?orders.map(o=>{const v=vendors.find(v=>v.id===o.vendor),canCancel=o.status==='reserved'&&Date.now()<Date.parse(o.date+'T20:30:00+05:30');return `<article class="order"><div class="order-details"><div class="eyebrow">${esc(o.status.replaceAll('_',' ').toUpperCase())} · DEMO</div><h2>${esc(v?.name)}</h2><p>${esc(o.name)} · ${esc(o.date)} · ₹99<br>Pickup 8:30–10:00 pm IST · ${esc(v?.area)}<br>No real food is reserved. Use the partner desk to simulate collection.</p></div><div class="order-code"><span>PICKUP CODE</span><b>${esc(o.id)}</b><span>No payment collected</span></div>${o.status==='reserved'?`<div class="order-actions"><button class="primary" data-reminder="${esc(o.id)}">Add pickup reminder</button>${canCancel?`<button class="secondary" data-cancel="${esc(o.id)}">Cancel bag</button>`:''}</div>`:''}</article>`}).join(''):'<div class="empty"><h2>Your next good bite is waiting.</h2><p>Choose a confirmed sample bag and try a reservation.</p><button class="primary" data-discover>Discover bags</button></div>'}
function download(body,type,name){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function reminder(id){const o=orders.find(o=>o.id===id);if(!o)return;const v=vendors.find(v=>v.id===o.vendor);const stamp=hour=>new Date(o.date+`T${hour}:00+05:30`).toISOString().replace(/[-:]/g,'').slice(0,15)+'Z';const now=new Date().toISOString().replace(/[-:]/g,'').slice(0,15)+'Z';const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//LastBite//Pickup//EN','BEGIN:VEVENT','UID:'+o.id+'@lastbite','DTSTAMP:'+now,'DTSTART:'+stamp('20:30'),'DTEND:'+stamp('22:00'),'SUMMARY:LastBite demo pickup - '+v.name,'LOCATION:'+v.area+' Ahmedabad (sample location)','DESCRIPTION:Demo only. Pickup code '+o.id+'. No payment collected. Exact address must be verified.','BEGIN:VALARM','TRIGGER:-PT30M','ACTION:DISPLAY','DESCRIPTION:LastBite pickup starts in 30 minutes','END:VALARM','END:VEVENT','END:VCALENDAR'].join('\r\n');download(text,'text/calendar;charset=utf-8',o.id+'-pickup.ics');toast('Import the downloaded event into your calendar to enable its reminder.')}
async function loadVendor(){const date=$('#stock-form input[name=date]').value;const data=await api('/api/vendor?date='+date,{operator:true});$('#vendor-slots').innerHTML=data.slots.length?data.slots.map(s=>`<p><b>${esc(vendors.find(v=>v.id===s.vendor)?.name)}</b> · ${s.quota} guaranteed · ${s.allocated} allocated · ${s.confirmed?'Confirmed':'Paused'}<br>${esc(s.address||'Pickup address not verified')}</p>`).join(''):'<p>No quota confirmed for this date. Set a minimum above.</p>';$('#vendor-orders').innerHTML=data.orders.length?data.orders.map(o=>`<article class="vendor-order"><b>${esc(o.id)}</b><span>${esc(vendors.find(v=>v.id===o.vendor)?.name)} · ${esc(o.status.replaceAll('_',' '))}</span>${o.status==='reserved'?`<div><button class="secondary" data-operator-order="${esc(o.id)}" data-status="collected">Simulate pickup</button><button class="secondary" data-operator-order="${esc(o.id)}" data-status="vendor_cancelled">Vendor cancellation</button><button class="secondary" data-operator-order="${esc(o.id)}" data-status="missed">Missed pickup</button></div>`:''}</article>`).join(''):'<p>No reservations for this date.</p>'}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.view)view(b.dataset.view);if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll('.chip').forEach(c=>c.classList.toggle('selected',c.dataset.filter===filter));render()}if(b.dataset.reserve)startReservation(b.dataset.reserve);if(b.classList.contains('close'))dialog.close();if(b.hasAttribute('data-discover'))view('discover');if(b.dataset.reminder)reminder(b.dataset.reminder);if(b.dataset.cancel){b.disabled=true;await api('/api/orders/cancel',{method:'POST',body:{id:b.dataset.cancel}});await Promise.all([loadOrders(),refresh()]);toast('Bag cancelled and released back to shared stock.')}if(b.dataset.operatorOrder){b.disabled=true;await api('/api/vendor/order',{method:'POST',operator:true,body:{id:b.dataset.operatorOrder,status:b.dataset.status}});await Promise.all([loadVendor(),loadOrders(),refresh()]);toast('Reservation updated. No payment or refund occurred.')}}catch(e){toast(e.message);b.disabled=false}});
$('#search').addEventListener('input',render);$('#sort').addEventListener('change',render);dateControl.addEventListener('change',refresh);$('#refresh-stock').addEventListener('click',refresh);
$('#reserve-form').addEventListener('submit',async e=>{e.preventDefault();const data=new FormData(e.target),button=e.target.querySelector('button[type=submit]');button.disabled=true;try{await api('/api/orders',{method:'POST',body:{vendor:selected.id,date:data.get('date'),name:data.get('name').trim(),agreed:true}});dialog.close();await Promise.all([loadOrders(),refresh()]);view('bags');toast('Demo bag reserved against shared stock. No payment collected.')}catch(e){$('#reserve-error').textContent=e.message;await refresh()}finally{button.disabled=false}});
$('#feedback').addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.target),body={intent:d.get('intent'),comment:d.get('comment').trim()},b=e.target.querySelector('.primary');b.disabled=true;try{await api('/api/feedback',{method:'POST',body});feedback.push({...body,createdAt:new Date().toISOString()});e.target.reset();$('#feedback-status').textContent='Feedback saved online for the pilot.'}catch(e){$('#feedback-status').textContent=e.message}finally{b.disabled=false}});
$('#export').addEventListener('click',()=>download(JSON.stringify({project:'LastBite',notice:'Shared demo reservations only; not real purchases or verified field results.',exportedAt:new Date().toISOString(),orders:orders.map(({name,...o})=>o),feedback},null,2),'application/json','LastBite-demo-evidence.json'));
$('#stock-form input[name=date]').value=nextDay();$('#stock-form input[name=date]').min=nextDay();$('#stock-form input[name=date]').max=dateControl.max;
$('#vendor-login').addEventListener('submit',async e=>{e.preventDefault();vendorKey=new FormData(e.target).get('key').trim();try{await loadVendor();$('#vendor-workspace').hidden=false;$('#vendor-status').textContent='Partner desk unlocked for this tab. The key is not saved.';e.target.reset()}catch(e){vendorKey='';$('#vendor-workspace').hidden=true;$('#vendor-status').textContent=e.message}});
$('#stock-form').addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.target),b=e.target.querySelector('.primary');b.disabled=true;try{await api('/api/vendor/stock',{method:'POST',operator:true,body:{vendor:d.get('vendor'),date:d.get('date'),quota:Number(d.get('quota')),address:d.get('address').trim(),confirmed:d.get('confirmed')==='on'}});$('#stock-status').textContent='Daily quota saved online. Confirmed bags are now reservable.';await Promise.all([loadVendor(),refresh()])}catch(e){$('#stock-status').textContent=e.message}finally{b.disabled=false}});
$('#stock-form input[name=date]').addEventListener('change',()=>loadVendor().catch(e=>toast(e.message)));
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'list_demo_bags',description:'Read shared sample bag availability; these are not real food offers.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({demo:true,date:dateControl.value,bags:vendors.map(v=>({id:v.id,name:v.name,portion:v.portion,diet:v.diet,remaining:slot(v)?.remaining||0,confirmed:!!slot(v)?.confirmed}))})})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'start_demo_reservation',description:'Open a form for an available sample bag. Does not reserve a bag or collect money.',inputSchema:{type:'object',properties:{id:{type:'string',enum:vendors.map(v=>v.id)}},required:['id'],additionalProperties:false},execute:input=>{if(!input||typeof input.id!=='string')throw Error('Bag id required');return startReservation(input.id)}})).catch(()=>{})}catch{}}
render();refresh();loadOrders();setInterval(()=>{if(!document.hidden)refresh()},30000);
